# Generated by Django 5.1.3 on 2025-03-14 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration_in_hours',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
