# Generated by Django 5.1.3 on 2025-03-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=50),
        ),
    ]
