# Generated by Django 5.1.6 on 2025-03-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challenge_duration_in_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
