# Generated by Django 5.1.3 on 2025-03-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_challenge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('0', '종료됨'), ('1', '진행중')], max_length=50),
        ),
    ]
