# Generated by Django 5.1.3 on 2025-03-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_challenge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('CL', 'closed'), ('PR', 'in-progress')], max_length=50),
        ),
    ]
