# Generated by Django 5.1.3 on 2025-03-21 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_challenge_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='duration_in_hours',
        ),
        migrations.AddField(
            model_name='challenge',
            name='current_participants',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
