# Generated by Django 5.1.3 on 2025-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_challenge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
